"""added some cols in URLAddresses

Revision ID: 6287f8e47d40
Revises: d1c6b8afdde2
Create Date: 2025-03-22 13:00:01.956410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6287f8e47d40'
down_revision: Union[str, None] = 'd1c6b8afdde2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('url', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('url', sa.Column('last_used_at', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'url', ['shorten_url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'url', type_='unique')
    op.drop_column('url', 'last_used_at')
    op.drop_column('url', 'created_at')
    # ### end Alembic commands ###
